### ISSUE TITLE
What's the point of multiple attempts in the retry loop?

### ISSUE THREAD

**Issue by dale-c-anderson** [robertdebock/docker-github-action-molecule#6]
Our use case is such that we want molecule to fail the first time when there is a problem. We don't want to reproduce the exact same failure 2 more times before the action stops. Doing so seems a waste of Github's compute resources, especially when testing against large strategy matrices. 

Can 
```
if [ $counter -ge 3 ] ;
``` 
be changed to accept an environment variable? E.g. 
```
if [ $counter -ge ${max_failures:-3} ] ;
``` 
?  I'd be happy to submit a PR.

**Comment by robertdebock** [comment]
Yes, that's a good plan. The intent of the retries is that when some remote resource (package repository for example) is unavailable, a few retries will be done.  It stabilize the results of the builds, but yes, costs a lot more time.

You can introduce the `max_failures` on this repository and pass the variable from the [molecule action](https://github.com/robertdebock/molecule-action).

When you've changed this repo, I'll release a new version, so that the [molecule action](https://github.com/robertdebock/molecule-action) can be changed.

Thanks!
