### ISSUE TITLE
Missing Dependency `rsync`

### ISSUE THREAD

**Issue by Melkor333** [robertdebock/docker-github-action-molecule#76]
hey Rob! :)

I'm trying to use this github action for molecule tests in an ansible collection. But apparently it doesn't work with "remote" images which it wants to fetch with `rsync`.

Is it possible to install `rsync` in the action container to circumvent this problem?

Edit: Forgot to add the link the the [non-working action](https://github.com/adfinis/ansible-collection-maintenance/actions/runs/3911894164/jobs/6685841449#step:6:202) (if it for some reason github doesn't jump to the proper line, it's the lines 191-195)

**Comment by robertdebock** [comment]
I think you are correct. I have `molecule/defaults/molecule.yml`: `pre_built_image` set to `yes`. This is because I want to start with an un-altered image. Setting `pre_built_image` to `no` or removing the parameter, causes Molecule to alter the image a bit, installing `python` and `sudo` if my memory serves me correctly.

Let met read a few things before deciding, but I think you are correct, `rsync` is likely required.

**Comment by Melkor333** [comment]
Thanks a lot, it works now! 🥳 🥳 🥳 🥳 🥳 🥳
